In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from os.path import exists

### Question 1
What's the version of Pandas that you installed?

In [3]:
pd.__version__

'1.5.3'

In [4]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"
my_file_path = "./housing.csv"

if exists(my_file_path) :
    print (my_file_path, "is exists")
else :
    #Get the link or url
    housing = requests.get(url, allow_redirects=True)
    #Save the content with name
    open('housing.csv', 'wb').write(housing.content)
       

./housing.csv is exists


In [5]:
df = pd.read_csv(my_file_path)

In [24]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object

In [6]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [8]:
df.info

<bound method DataFrame.info of        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  

### Question 2
How many columns are in the dataset?

In [9]:
df.shape[1]

10

### Question 3

Which columns in the dataset have missing values?

In [17]:
na = df.isna().sum().sort_values(ascending=False)
cols_miss_values = na[na > 0]
cols_miss_values

Series([], dtype: int64)

### Question 4

How many unique values does the `ocean_proximity` column have?

In [12]:
df.ocean_proximity.nunique() 

5

### Question 5

What's the average value of the `median_house_value` for the houses located near the bay?

In [18]:
df.loc[ df["ocean_proximity"] == "NEAR BAY" ] ["median_house_value"] .mean()


259212.31179039303

### Question 6

1. Calculate the average of `total_bedrooms` column in the dataset.
2. Use the `fillna` method to fill the missing values in `total_bedrooms` with the mean value from the previous step.
3. Now, calculate the average of `total_bedrooms` again.
4. Has it changed?

Has it changed?

#### Calculate the average of total_bedrooms column in the dataset

In [19]:
mean_total_bedrooms = df.total_bedrooms.mean()
mean_total_bedrooms.round(3)

537.871

#### Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.

In [20]:
df.total_bedrooms.fillna(mean_total_bedrooms, inplace=True)

#### Now, calculate the average of total_bedrooms again

In [21]:
mean_total_bedrooms = df.total_bedrooms.mean()
mean_total_bedrooms.round(3)

537.871

### Question 7

1. Select all the options located on islands.
2. Select only columns `housing_median_age`, `total_rooms`, `total_bedrooms`.
3. Get the underlying NumPy array. Let's call it `X`.
4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
5. Compute the inverse of `XTX`.
6. Create an array `y` with values `[950, 1300, 800, 1000, 1300]`.
7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
8. What's the value of the last element of `w`?

#### Select all the options located on islands.

In [22]:
df.loc[df['ocean_proximity'] =='ISLAND']

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

#### Select only columns `housing_median_age`, `total_rooms`, `total_bedrooms`.

In [25]:
mask_x = ['housing_median_age','total_rooms', 'total_bedrooms']
selected_df = df[mask_x ] 
selected_df

housing_median_age  total_rooms  total_bedrooms
0                    41.0        880.0           129.0
1                    21.0       7099.0          1106.0
2                    52.0       1467.0           190.0
3                    52.0       1274.0           235.0
4                    52.0       1627.0           280.0
...                   ...          ...             ...
20635                25.0       1665.0           374.0
20636                18.0        697.0           150.0
20637                17.0       2254.0           485.0
20638                18.0       1860.0           409.0
20639                16.0       2785.0           616.0

[20640 rows x 3 columns]

#### Get the underlying NumPy array. Let's call it `X`.

In [58]:
## convert to numpy array

#X = selected_df.to_numpy()
X = df[ ['total_rooms','total_bedrooms'] ].to_numpy()
X = X[:5]
X

array([[ 880.,  129.],
       [7099., 1106.],
       [1467.,  190.],
       [1274.,  235.],
       [1627.,  280.]])

In [59]:
X.shape

(5, 2)

#### Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.

In [60]:
# get transpose of X
X_transpo = X.T
XTX = np.dot(X_transpo, X)
XTX

array([[57592495.,  8998694.],
       [ 8998694.,  1409602.]])

#### Compute the inverse of `XTX`.

In [61]:
# Invert XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 6.84264739e-06, -4.36824650e-05],
       [-4.36824650e-05,  2.79571919e-04]])

In [62]:
XTX_inv.shape

(2, 2)

#### Create an array `y` with values `[950, 1300, 800, 1000, 1300]`.

In [63]:
y = np.array([950, 1300, 800, 1000, 1300])
y
y.shape

(5,)

#### Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.

In [64]:
#A = XTX_inv.dot(xT)
#x = np.dot(XTX_inv,X_transpo)
x = XTX_inv.dot(X_transpo)
x

array([[ 0.00038649,  0.00026315,  0.0017385 , -0.00154785, -0.0010981 ],
       [-0.00237579, -0.00089528, -0.01096351,  0.01004794,  0.00720877]])

In [65]:
x.shape

(2, 5)

In [66]:
w = x.dot(y)
#w = x * y
w


array([-0.87532502,  7.22766568])

#### What's the value of the last element of `w`?

In [67]:
w[-1]

7.227665677845319